config/routes.rb
Rails.application.routes.draw do
  root 'flights#search'
  resources :flights 
  resources :bookings
  resources :passengers
  get '/search', to: 'flights#search', as: :search
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: 'from_airport_id', class_name: 'Flight'
  has_many :arriving_flights, foreign_key: 'to_airport_id', class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: 'Airport'
  belongs_to :to_airport, class_name: 'Airport'
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def show
		@booking = Booking.find(params[:id])
	end
	
	def new
    @flight = Flight.find(params[:flight_id])
    @passenger_num = params[:passengers].to_i
		
		@booking = Booking.new(flight_id: @flight.id)
		@passenger_num.times { @booking.passengers.build }
	end

	def create
    @booking = Booking.new(bookings_params)
		@booking.save
		redirect_to booking_path(@booking)
	end

  def bookings_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email, :_destroy])
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def search
    @airport_options = Airport.all.map { |a| [a.name, a.id] }
    @passenger_options = [[1], [2], [3], [4]]
    @date_options = Flight.all.map { |f| [f.start_date.strftime('%b %d, %Y'), f.start_date] }.uniq
    if params[:search]
      parsed_datetime = DateTime.parse(params[:start_date])
      @flights = Flight.where(
        from_airport: params[:from_airport],
        to_airport: params[:to_airport],
        start_date: parsed_datetime..(parsed_datetime + 1.day)
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Your Flight</h1>
<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Departs</th>
      <th>Arrives</th>
      <th>Date</th>
      <th>Time</th>
      <th>Duration</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @flight.id%></td>
        <td><%= @flight.from_airport.name%></td>
        <td><%= @flight.to_airport.name%></td>
        <td><%= @flight.start_date.strftime('%b %d, %Y')%></td>
        <td><%= @flight.start_date.strftime('%H:%M%P') %></td>
        <td><%= @flight.duration%> Hours</td>
      </tr>
  <tbody>
</table>

<h2>Passenger Info<h2>
<%= form_for @booking do |f| %>
  <%= f.fields_for :passengers do |p| %>
    <%= p.label :name%>
    <%= p.text_field :name%><br>

    <%= p.label :email%>
    <%= p.text_field :email %><br><br>
  <% end %>
  <%= f.hidden_field :flight_id, value: params[:flight_id] %>
  <%= f.submit 'Submit' %><br>
<% end %>

app/views/bookings/show.html.erb
<% @booking.passengers.each do |passenger| %>
<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Departs</th>
      <th>Arrives</th>
      <th>Date</th>
      <th>Time</th>
      <th>Duration</th>
      <th>Passenger Name</th>
      <th>Passenger Email</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @booking.flight.id%></td>
        <td><%= @booking.flight.from_airport.name%></td>
        <td><%= @booking.flight.to_airport.name%></td>
        <td><%= @booking.flight.start_date.strftime('%b %d, %Y')%></td>
        <td><%= @booking.flight.start_date.strftime('%H:%M%P') %></td>
        <td><%= @booking.flight.duration%> Hours</td>
        <td><%= passenger.name.titleize %></td>
        <td><%= passenger.email %></td>
      </tr>
  <tbody>
</table>
<% end %>

app/views/flights/_flights.html.erb
<h4><%= pluralize(@flights.count, 'flight') %> matched your search </h4>

<% if @flights.any? %>
<table>
  <thead>
    <tr>
      <th>Flight</th>
      <th>Departs</th>
      <th>Arrives</th>
      <th>Date</th>
      <th>Time</th>
      <th>Duration</th>
    </tr>
  </thead>
  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.id%></td>
        <td><%= flight.from_airport.name%></td>
        <td><%= flight.to_airport.name%></td>
        <td><%= flight.start_date.strftime('%b %d, %Y')%></td>
        <td><%= flight.start_date.strftime('%H:%M%P') %></td>
        <td><%= flight.duration%> Hours</td>
        <td>
          <%= form_with url: new_booking_path, method: 'get', local: true do %>
            <%= hidden_field_tag :passengers, params[:passengers] %>
            <%= hidden_field_tag :flight_id, flight.id %>
            <%= submit_tag 'Book Flight' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <tbody>
</table>
<% end %>

app/views/flights/search.html.erb
<h1>Search Flights</h1>
<%= form_with url: '/search', method: :get, local: true do %>
  <%= hidden_field_tag :search, 'true' %>
  <h2>From:</h2>
  <%= select_tag(:from_airport, options_for_select(@airport_options), include_blank: "Select airport")%>
  <h2>To:</h2>
  <%= select_tag(:to_airport, options_for_select(@airport_options), include_blank: "Select airport")%><br><br>
  <h2>Flight Date</h2>
  <%= select_tag(:start_date, options_for_select(@date_options), { prompt: "Date:" }) %><br><br>
  <h2>Passengers<h2>
  <%= select_tag(:passengers, options_for_select(@passenger_options))%><br><br>
  <%= submit_tag 'Search' %>
<% end %>

<%= render 'flights' if @flights%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>